#  refine all update functions which will be used in apis-emulator/inputData.py

## sample data func

In [3]:
import os
import pandas as pd
import numpy as np

import logging.config, datetime
logger = logging.getLogger(__name__)

import matplotlib.pyplot as plt
%matplotlib inline

In [4]:
cols = list(range(6, 52+1, 2))
cols.insert(0, 1)
demand_data = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_load_data.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')

In [14]:
def old_loadDemand_Sample():
    global demand

    demand = {}
    # demand_data = np.genfromtxt('data/input/Sample/sample_load_data.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
    cols = list(range(6, 52+1, 2))
    cols.insert(0, 1)
    # print(cols)
    # read column 2, col 7~53 for every 2 cols (1 hour per data point) from input data
    # replace our own data files to the /Sample/ folder
    demand_data = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_load_data.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')
    # print(demand_data)
    
    
    for row in demand_data:
#         print(int(row[0]), row)
        cus_id = "E{0:03d}".format(int(row[0]))
#         print("cus_id", cus_id)
        # print(demand.get(cus_id))
        # print(type(demand))
        if not demand.get(cus_id):
            demand[cus_id] = []
        demand[cus_id].append(row[1:])
#         print(demand[cus_id])
        
#     print("all id", demand)
    
    for cus_id in demand:
        demand[cus_id] = np.array(demand[cus_id])
        displayNames[cus_id] = "Sample_"+cus_id

    return demand

In [15]:
displayNames = {}
sample_load = old_loadDemand_Sample()
print(sample_load["E004"], '\n', type(sample_load), '\n', len(sample_load['E001']))
# print(len(sample_load["E001"]))

[[0.33 0.24 0.23 ... 0.26 0.66 0.25]
 [0.23 0.29 0.25 ... 0.69 0.61 0.29]
 [0.27 0.22 0.22 ... 1.3  1.19 1.11]
 ...
 [0.35 0.25 0.25 ... 1.26 1.23 0.62]
 [0.46 0.42 0.41 ... 1.01 1.06 0.77]
 [0.43 0.38 0.42 ... 0.92 0.63 0.35]] 
 <class 'dict'> 
 365


## our data update function

In [2]:
inputdata = pd.read_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/fourhouses_2019_apis_load_reform.csv')
# print(inputdata.iloc[0, 1568])

# inputdata = inputdata.fillna(method="ffill", axis=1, inplace=False)
# inputdata.iloc[0, 1568]
# print(len(inputdata.columns))
# print(inputdata.iloc[0, 2881])


In [10]:
# forward fill all NaN values and output new csv files
inputdata = pd.read_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/fourhouses_2019_apis_load_reform.csv')
inputdata = inputdata.fillna(method="ffill", axis=1, inplace=False)
inputdata.insert(0, "LoadData", "LoadData")
inputdata.to_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/fourhouses_2019_apis_load_reform.csv', index=False)
# print(inputdata)

In [24]:
# cols = list(range(3, 2880+3, 1))
cols = list(range(2, 2880+2, 1))
cols.insert(0, 0)
# print(cols)
# read column 1, col 3~2882(end) for each cols (30s per data point) from input data
pv_data = np.loadtxt(
'/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/fourhouses_2019_apis_load_reform.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')

In [26]:
print(pv_data[1], len(pv_data[1]))
oneday = pv_data[1]

[212. 124. 121. ... 126. 126. 387.] 2881


In [25]:
def PV_data():  # load house's PV production data
    global pv
    pv = {}

    cols = list(range(2, 2880+2, 1))
    cols.insert(0, 0)
    # print(cols)
    # read column 0, col 2~2881(end) for each cols (30s per data point) from input data
    pv_data = np.loadtxt(
        '/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/fourhouses_2019_apis_sol_reform.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')
    # our_data_all = our_data_all.fillna(method="ffill", inplace=False)
    # our_data = our_data_all['pvc_charge_power'].values
    # print(pv_data) 

    for row in pv_data:
#         print(int(row[0]), row)
        cus_id = "E{0:03d}".format(int(row[0]))
        # print("cus_id", cus_id)
        # print(type(pv))
        if not pv.get(cus_id):
            pv[cus_id] = []
        pv[cus_id].append(row[1:])
        # print(pv[cus_id])
        
#     print("all id", demand)
    
    for cus_id in pv:
        pv[cus_id] = np.array(pv[cus_id])
        displayNames[cus_id] = "Oist_"+cus_id

    return pv
        

In [26]:
displayNames = {}
pv_oist = PV_data()
# print(pv_oist["E212"])


[[212.   0.   0. ...   0.   0.   0.]
 [212.   0.   0. ...   0.   0.   0.]
 [212.   0.   0. ...   0.   0.   0.]
 ...
 [215.   0.   0. ...   0.   0.   0.]
 [215.   0.   0. ...   0.   0.   0.]
 [215.   0.   0. ...   0.   0.   0.]]


In [6]:
def Load_data():  # load house's PV production data
    global load
    load = {}

    cols = list(range(2, 2880+2, 1))
    cols.insert(0, 0)
    # read column 0, col 2~2881(end) for each cols (30s per data point) from input data
    load_data = np.loadtxt(
        '/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/fourhouses_2019_apis_load_reform.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')

    for row in load_data:
        cus_id = "E{0:03d}".format(int(row[0]))
        if not load.get(cus_id):
            load[cus_id] = []
        load[cus_id].append(row[1:])
        
    for cus_id in load:
        load[cus_id] = np.array(load[cus_id])
        displayNames[cus_id] = "Oist_"+cus_id

    return load

In [7]:
displayNames = {}
load_oist = Load_data()

# Update functions

In [36]:
def old_demandUpdate_Sample():
    count_h = float(count_s)/3600
    weight = count_h-int(count_h)
    step_now = int((count_h) / 24), int((count_h) % 24)
    step_next = (int((count_h+1) / 24), int((count_h+1) % 24))
    print(step_now, step_next)

    # if int(count_h+1) >= demand[next(iter(oesunits))].size:
    #     logger.debug("no more demand data")
    #     return False
    for oesid in oesunits:
        oesunits[oesid]["emu"]["ups_output_power"] = \
            round(((1-weight)*demand[oesid][step_now] + weight*demand[oesid][step_next])*1000, 2)  # demand[W]

    print("load[step_now]", demand[oesid][step_now], "\n", "load[step_next]", demand[oesid][step_next])
    print("pvc power", round((1-weight)*demand[oesid][step_now] + weight*demand[oesid][step_next], 2))
    print((1-weight)*demand[oesid][step_now] + weight*demand[oesid][step_next])
    return True

In [38]:
count_s = 525600 * 60 - 3600*9.5   # how many seconds have passed
count_h = float(count_s) / 3600
print("count_h = {:.4f} hours".format(count_h))
oesunits = {}

cols = list(range(6, 52+1, 2))
cols.insert(0, 1)
# read column 2, col 7~53 for every 2 cols (1 hour per data point) from input data
# replace our own data files to the /Sample/ folder
demand_data = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_load_data.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')
    
# sol = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_solar_data.csv', delimiter=',')
# print("demand_data.size: ", demand_data.size, "\n", "data size is {:.0f} days".format(int(sol.size/24)))

load = old_demandUpdate_Sample()
print(load)

count_h = 8750.5000 hours
(364, 14) (364, 15)


TypeError: 'set' object is not subscriptable

In [34]:
def PVUpdate():
    # count_s = 3600*12 # how many seconds have passed
    count_t = float(count_s) / 30  # set counter for data which is collected every 30s
    weight = count_t - int(count_t)

    step_now = int((count_t) / 2880), int((count_t) % 2880)
    step_next = (int((count_t+1) / 2880), int((count_t+1) % 2880))

    # step_now = (int((count_t) / 2880) ) * int((count_t) % 2880)
    # step_next = (int((count_t + 1) / 2880) ) * int((count_t + 1) % 2880)
    print(step_now, step_next)

    # if int(count_t + 1) >= pv[next(iter(oesunits))].size:
    #     logger.debug("no more our_data radiation data")
    #     return False
    # for oesid in oesunits:
    #     oesunits[oesid]["emu"]["pvc_charge_power"] = round(
    #         (1 - weight) * pv[oesid][step_now] + weight * pv[oesid][step_next], 2)  # our_data[W]

    print("our_data[step_now]", our_data[step_now], "\n", "our_data[step_next]", our_data[step_next])
    print("pvc power", round((1 - weight) * our_data[step_now] + weight * our_data[step_next], 2))
    print((1 - weight) * our_data[step_now] + weight * our_data[step_next])

    return True

In [35]:
# our_data_all = pd.read_csv('/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_all.csv')
# our_data_all = our_data_all.fillna(method="ffill", inplace=False)
# our_data = our_data_all['ups_output_power'].values

# # data_h212 = np.loadtxt("/Users/Huang/Documents/DQNBattery/data/house212_2019_sift/house212_20190101.csv")
# print(our_data, "data size is", our_data.size, type(our_data))  # 0~2879
# print(our_data[1566])
# # pvc_212 = data_h212[""]
# # plt.plot(our_data)
# # plt.show()

count_s = 3600*24 - 30*1000.5 # how many seconds have passed
# count_t = float(count_s)/30  # set counter for data which is collected every 30s
# print(count_t)
# weight = count_t-int(count_t)
# print("weight: ", weight)

oesunits = {}

solar = PVUpdate()
# print(solar)

(0, 1879) (0, 1880)
