#  refine all update functions which will be used in apis-emulator/inputData.py

## sample data func

In [8]:
import os
import pandas as pd
import numpy as np

import logging.config, datetime
logger = logging.getLogger(__name__)

import matplotlib.pyplot as plt
%matplotlib inline

In [12]:
def old_loadDemand_Sample():
    global demand

    demand = {}
    # demand_data = np.genfromtxt('data/input/Sample/sample_load_data.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
    cols = list(range(6, 52+1, 2))
    cols.insert(0, 1)
    print(cols)
    # read column 2, col 7~53 for every 2 cols (1 hour per data point) from input data
    # replace our own data files to the /Sample/ folder
    demand_data = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_load_data.csv', delimiter=',', skiprows=1, usecols=cols, encoding='utf8')
    print(demand_data)
    
    
    for row in demand_data:
#         print(int(row[0]), row)
        cus_id = "E{0:03d}".format(int(row[0]))
#         print("cus_id", cus_id)
        if not demand.get(cus_id):
            demand[cus_id] = []
        demand[cus_id].append(row[1:])
#         print(demand[cus_id])
        
#     print("all id", demand)
    
    for cus_id in demand:
        demand[cus_id] = np.array(demand[cus_id])
        displayNames[cus_id] = "Sample_"+cus_id

    return demand

In [14]:
displayNames = {}
sample_load = old_loadDemand_Sample()
display(sample_load["E001"])
# print(len(sample_load["E001"]))

[1, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
[[  1.     0.13   0.13 ...   0.13   0.11   0.11]
 [  1.     0.13   0.13 ...   0.13   0.13   0.13]
 [  1.     0.14   0.14 ...   0.15   0.16   0.13]
 ...
 [100.     0.13   0.13 ...   0.49   0.5    0.91]
 [100.     0.13   0.13 ...   0.43   0.39   1.31]
 [100.     0.15   0.11 ...   0.55   1.25   0.61]]


array([[0.13, 0.13, 0.13, ..., 0.13, 0.11, 0.11],
       [0.13, 0.13, 0.13, ..., 0.13, 0.13, 0.13],
       [0.14, 0.14, 0.13, ..., 0.15, 0.16, 0.13],
       ...,
       [0.25, 0.23, 0.22, ..., 0.24, 0.24, 0.22],
       [0.2 , 0.2 , 0.18, ..., 0.23, 0.23, 0.26],
       [0.17, 0.17, 0.21, ..., 0.26, 0.25, 0.27]])