# Houses info
<!-- ![landscape of faculty houses](landscape.png) -->
<img src="landscape.png" alt="landscape" width="600"/>

load data and solar data, same data in a year/month (2019),
house 212, 213, 214, 215 (205, 206, 208) pick these 4 houses to replace the sample data,
only load data is needed (w.r.t the form of sample data, house ID needed)

In [1]:
import os
import pandas as pd
import numpy as np

import logging.config, datetime
logger = logging.getLogger(__name__)

import matplotlib.pyplot as plt
%matplotlib inline

In [90]:
house212_2019 = '/Users/Huang/Documents/DQNBattery/data/house212_2019_sift'
house213_2019 = '/Users/Huang/Documents/DQNBattery/data/house213_2019_sift'
house214_2019 = '/Users/Huang/Documents/DQNBattery/data/house214_2019_sift'
house215_2019 = '/Users/Huang/Documents/DQNBattery/data/house215_2019_sift'

house205_2019 = '/Users/Huang/Documents/DQNBattery/data/house205_2019_sift'
house206_2019 = '/Users/Huang/Documents/DQNBattery/data/house206_2019_sift'
house208_2019 = '/Users/Huang/Documents/DQNBattery/data/house208_2019_sift'

# weather 
weather_2019 = '/Users/Huang/Documents/DQNBattery/data/2019_hillside_weather'

In [3]:
os.chdir(house215_2019)  # path of original csv data files
# name = os.path.splitext(raw_data_dir)[0]  # get file name
raw_data_dir = os.getcwd()  # read current file path

file_list = os.listdir(raw_data_dir)

for path in file_list:
    data = pd.read_csv(path)
    if len(data) != 2880:
        print(path)
    

In [4]:
odd_data = pd.read_csv('/Users/Huang/Documents/DQNBattery/data/house215_2019_sift/house215_20190605.csv')
time = odd_data["timestamp"]


In [17]:
timestamp2 = pd.date_range("2019-06-05 00:00:00","2019-06-05 23:59:59",freq='30S')
timestamp2 = pd.DataFrame(timestamp2)
# ['txt'].str.len()

# time2 = timestamp2.values
# print(timestamp2)

timestamp = pd.date_range("00:00:00", "23:59:59", freq="30S").strftime('%H:%M:%S')
timestamp = pd.DataFrame(timestamp)
# display(timestamp)

timestamp.to_csv('/Users/Huang/Desktop/test.csv')

In [91]:
def get_file_house(foldername, houseID):
    
    file_list = []  # file name stored in file_list
   
    for root, dirs, files in os.walk(foldername):
        for file in files:
            dirname, filename = os.path.split(file)

#             print(filename.split('2019', 1)[0])
            if filename.split('_', 1)[0] == houseID:
                filename = filename.split('_', 1)[1]        
                file_list.append(filename.split('.', 1)[0])

    file_list.sort()
    
    return file_list

In [92]:
def get_file_weather(foldername, houseID):
    
    file_list = []  # file name stored in file_list
   
    for root, dirs, files in os.walk(foldername):
        for file in files:
            dirname, filename = os.path.split(file)
            
#             print(filename)
#             print(filename.split('2019', 1)[0])      

            if filename.split('2019', 1)[0] == houseID:
                filename = filename.split('weather', 1)[1]        
                file_list.append(filename.split('.', 1)[0])

    file_list.sort()
    
    return file_list

In [93]:
house212_files = get_file_house(house212_2019, "house212")
house213_files = get_file_house(house213_2019, "house213")
house214_files = get_file_house(house214_2019, "house214")
house215_files = get_file_house(house215_2019, "house215")

weather_files = get_file_weather(weather_2019, "weather")

print("weather:", len(weather_files), "\n",
      "house212", len(house212_files), "\n",
      "house213", len(house213_files), "\n",
      "house214", len(house214_files), "\n",
      "house215", len(house215_files))

weather: 334 
 house212 344 
 house213 346 
 house214 334 
 house215 345


# Get the common date files

In [94]:
common = list(set(weather_files)&set(house212_files)&set(house213_files)&set(house214_files)&set(house215_files))
print(len(common))

332


In [95]:
common.sort()
# print(common)

# generate APIS data

In [10]:
def gener_apis(houseID, common_list, inputfile_dir, outputfile_dir, outputfile_name):
    # join all common dates data into one single file for each node
    
    df = pd.read_csv(inputfile_dir + '/' + houseID + common_list[0] + ".csv")

    df.to_csv(outputfile_dir + '/' + outputfile_name, index=False)

    for i in range(1, len(common_list)):
        df = pd.read_csv(inputfile_dir + '/' + houseID + common_list[i] + ".csv", error_bad_lines=False)
        df.to_csv(outputfile_dir + '/' + outputfile_name, index=False, header=False, mode='a+')


In [11]:
common_list = common

house212_inputfile_dir = '/Users/Huang/Documents/DQNBattery/data/house212_2019_sift'
house212_outputfile_dir = '/Users/Huang/Documents/DQNBattery/data'
house212_outputfile_name = 'house212_2019_apis_all.csv'

house212_apis = gener_apis("house212_", common, house212_inputfile_dir, house212_outputfile_dir, house212_outputfile_name)


In [11]:
house213_inputfile_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_sift'
house213_outputfile_dir = '/Users/Huang/Documents/DQNBattery/data'
house213_outputfile_name = 'house213_2019_apis_all.csv'

house213_apis = gener_apis("house213_", common, house213_inputfile_dir, house213_outputfile_dir, house213_outputfile_name)


In [12]:
house214_inputfile_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_sift'
house214_outputfile_dir = '/Users/Huang/Documents/DQNBattery/data'
house214_outputfile_name = 'house214_2019_apis_all.csv'

house214_apis = gener_apis("house214_", common, house214_inputfile_dir, house214_outputfile_dir, house214_outputfile_name)


In [12]:
house215_inputfile_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_sift'
house215_outputfile_dir = '/Users/Huang/Documents/DQNBattery/data'
house215_outputfile_name = 'house215_2019_apis_all.csv'

house215_apis = gener_apis("house215_", common, house215_inputfile_dir, house215_outputfile_dir, house215_outputfile_name)


In [14]:
weather_inputfile_dir = '/Users/Huang/Documents/DQNBattery/data/2019_hillside_weather'
weather_outputfile_dir = '/Users/Huang/Documents/DQNBattery/data'
weather_outputfile_name = 'weather_2019_apis_all.csv'

weather_apis = gener_apis("weather", common, weather_inputfile_dir, weather_outputfile_dir, weather_outputfile_name)


# take average value for every 30 mins

In [13]:
def timeframe(timestep, inputdata):
    # select the timestamp with every timestep mins
    # slice data for every 15 minutes
    # raw data recorded for each 30s, ~ slice data for every timestep*2 rows
    step = np.arange(0, len(inputdata), timestep * 2)
    outputdata = inputdata.loc[step, :]
    outputdata.index = range(len(outputdata))  # do not keep original index
    return outputdata

In [14]:
def timeframe_avg(timestep, inputdata):
    inputdata = inputdata.fillna(method='ffill', inplace=False)
    avg = inputdata.groupby(inputdata.index // (timestep * 2)).mean()
    timestamp = timeframe(timestep, inputdata)
    time = timestamp[['timestamp']]
    outputdata = pd.concat((time, avg), axis=1)
    return outputdata

In [15]:
timestep = 30

house212_ess_dir = '/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_all.csv'
house212_inputdata = pd.read_csv(house212_ess_dir)
house212_outputdata = timeframe_avg(timestep, house212_inputdata)
house212_outputdata.to_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/house212_2019_avg.csv', index=False)


In [16]:
house213_ess_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_apis_all.csv'
house213_inputdata = pd.read_csv(house213_ess_dir)
house213_outputdata = timeframe_avg(timestep, house213_inputdata)
house213_outputdata.to_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/house213_2019_avg.csv', index=False)


In [17]:
house214_ess_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_apis_all.csv'
house214_inputdata = pd.read_csv(house214_ess_dir)
house214_outputdata = timeframe_avg(timestep, house214_inputdata)
house214_outputdata.to_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/house214_2019_avg.csv', index=False)


In [18]:
house215_ess_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_apis_all.csv'
house215_inputdata = pd.read_csv(house215_ess_dir)
house215_outputdata = timeframe_avg(timestep, house215_inputdata)
house215_outputdata.to_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/house215_2019_avg.csv', index=False)


In [19]:
weather_ess_dir = '/Users/Huang/Documents/DQNBattery/data/weather_2019_apis_all.csv'
weather_inputdata = pd.read_csv(weather_ess_dir)
weather_outputdata = timeframe_avg(timestep, weather_inputdata)
weather_outputdata.to_csv('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/weather_2019_avg.csv', index=False)


## change the format the same as Sample data
**Basically we need to transpose the data file**

**load for each house**

In [69]:
def reformat_oneday_load(input_dir, output_dir):
    
    os.chdir(input_dir) # e.g. house215_2019_sift
    file_list = os.listdir()
    file_list.sort()  # sort all data (from 01/01 to 12/31)
    
    for i in range(len(file_list)):
        data = pd.read_csv(input_dir + '/' + file_list[i], error_bad_lines=False)
        
        df = pd.DataFrame(data, columns=["timestamp", "ups_output_power"])
        df2 = pd.DataFrame(data, columns=["ups_output_power"])
        date = pd.to_datetime(df['timestamp'][0]).date()
        
        d = date.strftime("%Y/%m/%d")  # change index to str

        df_t = pd.DataFrame((df.T).iloc[1])#, columns = column_name)
        df_t = df_t.T # transpose the dataframe

        df_t.insert(0,'date', d)
        
        df_t.to_csv(output_dir + '/' + file_list[i])#, header=False)
        
#         df_t.to_csv('/Users/Huang/Desktop/testoneday2.csv', header=False)

In [75]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_apis_load/'

reformat_oneday_load(input_dir, output_dir)

In [76]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_apis_load/'

reformat_oneday_load(input_dir, output_dir)

In [77]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_apis_load/'

reformat_oneday_load(input_dir, output_dir)

In [ ]:
# input_dir = '/Users/Huang/Documents/DQNBattery/data/2019_hillside_weather/'
# output_dir = '/Users/Huang/Documents/DQNBattery/data/2019_hillside_weather_sift_apis/'

# reformat_oneday(input_dir, output_dir)

## solar power data
**get from pvc_charge_power**

In [78]:
def reformat_oneday_sol(input_dir, output_dir):
    
    os.chdir(input_dir) # e.g. house215_2019_sift
    file_list = os.listdir()
    file_list.sort()  # sort all data (from 01/01 to 12/31)
    
    for i in range(len(file_list)):
        data = pd.read_csv(input_dir + '/' + file_list[i], error_bad_lines=False)
        
        df = pd.DataFrame(data, columns=["timestamp", "pvc_charge_power"])
#         df2 = pd.DataFrame(data, columns=["pvc_charge_power"])
        date = pd.to_datetime(df['timestamp'][0]).date()
        
        d = date.strftime("%Y/%m/%d")  # change index to str

        df_t = pd.DataFrame((df.T).iloc[1])#, columns = column_name)
        df_t = df_t.T # transpose the dataframe

        df_t.insert(0,'date', d)
        
        df_t.to_csv(output_dir + '/' + file_list[i])#, header=False)

In [80]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house212_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_sol/'

reformat_oneday_sol(input_dir, output_dir)

In [81]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_apis_sol/'

reformat_oneday_sol(input_dir, output_dir)

In [82]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_apis_sol/'

reformat_oneday_sol(input_dir, output_dir)

In [83]:
input_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_sift/'
output_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_apis_sol/'

reformat_oneday_sol(input_dir, output_dir)

## reform to one file

In [122]:
def onehouse(input_file):
    
    data = pd.read_csv(input_file)
    
    return data

In [123]:
input_212 = '/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_sol_reform.csv'
input_213 = '/Users/Huang/Documents/DQNBattery/data/house213_2019_apis_sol_reform.csv'
input_214 = '/Users/Huang/Documents/DQNBattery/data/house214_2019_apis_sol_reform.csv'
input_215 = '/Users/Huang/Documents/DQNBattery/data/house215_2019_apis_sol_reform.csv'

In [124]:
output_212 = onehouse(input_212)
output_213 = onehouse(input_213)
output_214 = onehouse(input_214)
output_215 = onehouse(input_215)

/Users/Huang/opt/miniconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3263: DtypeWarning: Columns (915,978,997,1000,1001,1019,1054,1062,1063,1088,1092,1094,1097,1101,1102,1137,1140,1151,1152,1153,1154,1171,1188,1206,1208,1210,1212,1215,1226,1247,1257,1264,1268,1277,1291,1292,1297,1299,1303,1304,1305,1306,1313,1316,1319,1323,1328,1334,1336,1337,1338,1341,1344,1347,1351,1356,1362,1366,1367,1371,1376,1377,1382,1384,1387,1388,1391,1393,1397,1399,1401,1403,1404,1405,1407,1408,1410,1411,1412,1413,1414,1416,1418,1419,1422,1423,1428,1435,1438,1441,1443,1444,1448,1449,1450,1452,1453,1456,1458,1460,1461,1462,1463,1464,1465,1467,1472,1473,1477,1483,1485,1488,1489,1493,1496,1498,1499,1502,1503,1504,1506,1507,1511,1512,1515,1518,1520,1522,1523,1524,1526,1528,1529,1530,1536,1537,1538,1541,1544,1547,1549,1554,1555,1560,1561,1563,1564,1567,1569,1570,1575,1577,1579,1581,1584,1585,1587,1588,1592,1593,1598,1599,1601,1603,1604,1609,1613,1614,1615,1616,1620,1621,1622,1623

In [121]:
output_all = output_212.append(output_213).append(output_214).append(output_215)
# display(test[956150:956170])

outputfile_name = 'fourhouses_2019_apis_load_reform.csv'
output_all.to_csv('/Users/Huang/Documents/DQNBattery/data/' + outputfile_name, index=False)

In [125]:
output_all = output_212.append(output_213).append(output_214).append(output_215)
# display(test[956150:956170])

outputfile_name = 'fourhouses_2019_apis_sol_reform.csv'
output_all.to_csv('/Users/Huang/Documents/DQNBattery/data/' + outputfile_name, index=False)

In [112]:
# put apis data into one file for each house
# share the same date!!
def house_apis_all(houseID, common_list, input_data_dir, output_data_dir, output_name):
    os.chdir(input_data_dir) # e.g. house215_2019_sift
    file_list = os.listdir()
    file_list.sort()  # sort all data (from 01/01 to 12/31)
    
    df = pd.read_csv(input_data_dir + '/' + houseID + common_list[0] + '.csv')

    df.to_csv(output_data_dir + '/' + output_name, index=False)
    
    for i in range(1, len(common_list)):
        df = pd.read_csv(input_data_dir + '/' + houseID + common_list[i] + '.csv', error_bad_lines=False)
#         df = pd.DataFrame(data)
        
        df.to_csv(output_data_dir + '/' + output_name, index=False, header=False, mode='a+')
            

In [113]:
input_data_dir = '/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_sol'
output_name = 'house212_2019_apis_sol_reform.csv'
output_data_dir = '/Users/Huang/Documents/DQNBattery/data'

house_apis_all('house212_', common, input_data_dir, output_data_dir, output_name)

In [114]:
input_data_dir = '/Users/Huang/Documents/DQNBattery/data/house213_2019_apis_sol'
output_name = 'house213_2019_apis_sol_reform.csv'
output_data_dir = '/Users/Huang/Documents/DQNBattery/data'

house_apis_all('house213_', common, input_data_dir, output_data_dir, output_name)

In [115]:
input_data_dir = '/Users/Huang/Documents/DQNBattery/data/house214_2019_apis_sol'
output_name = 'house214_2019_apis_sol_reform.csv'
output_data_dir = '/Users/Huang/Documents/DQNBattery/data'

house_apis_all('house214_', common, input_data_dir, output_data_dir, output_name)

In [116]:
input_data_dir = '/Users/Huang/Documents/DQNBattery/data/house215_2019_apis_sol'
output_name = 'house215_2019_apis_sol_reform.csv'
output_data_dir = '/Users/Huang/Documents/DQNBattery/data'

house_apis_all('house215_', common, input_data_dir, output_data_dir, output_name)

In [2]:
timestamp = pd.date_range("00:00:00", "23:59:59", freq="30S").strftime('%H:%M:%S')
display(timestamp)


Index(['00:00:00', '00:00:30', '00:01:00', '00:01:30', '00:02:00', '00:02:30',
       '00:03:00', '00:03:30', '00:04:00', '00:04:30',
       ...
       '23:55:00', '23:55:30', '23:56:00', '23:56:30', '23:57:00', '23:57:30',
       '23:58:00', '23:58:30', '23:59:00', '23:59:30'],
      dtype='object', length=2880)

In [68]:
testfile = '/Users/Huang/Documents/DQNBattery/data/house215_2019_sift/house215_20190102.csv'
testdata = pd.read_csv(testfile)
testdata = testdata.fillna(method="ffill", inplace=False)
# display(testdata)

# take date
df = pd.DataFrame(testdata, columns=["timestamp", "ups_output_power"])
df2 = pd.DataFrame(testdata, columns=["ups_output_power"])
# display(df2.T)

date = pd.to_datetime(df['timestamp'][0]).date()
print(date, type(date)) # 2019-01-01
d = date.strftime("%Y/%m/%d")
# now.strftime('%Y-%m-%d')
print(d, type(d))
                

# build new csv file (load)
# column_name =  ['houseID', 'Number', "date", timestamp]
# column_name = {timestamp}
# print(column_name)

df_t = pd.DataFrame((df.T).iloc[1])#, columns = column_name)
df_t = df_t.T
# df_t.rename(columns={'ups_output_power': 'house'})
print(df_t)
df_t.insert(0,'date', d)
display(df_t)

df_t.to_csv('/Users/Huang/Desktop/testoneday2.csv')#, header=False)

# df_t.rename(columns=column_name)
# display(df_t)



2019-01-02 <class 'datetime.date'>
2019/01/02 <class 'str'>
                  0     1     2     3     4     5     6     7     8     9     \
ups_output_power  2842  2821  2812  2820  3015  2944  2997  2986  2970  2983   

                  ...  2870 2871 2872 2873 2874  2875  2876 2877 2878 2879  
ups_output_power  ...  1217  939  844  836  796  1357  1324  872  863  933  

[1 rows x 2880 columns]


date     0     1     2     3     4     5     6     7  \
ups_output_power  2019/01/02  2842  2821  2812  2820  3015  2944  2997  2986   

                     8  ...  2870 2871 2872 2873 2874  2875  2876 2877 2878  \
ups_output_power  2970  ...  1217  939  844  836  796  1357  1324  872  863   

                 2879  
ups_output_power  933  

[1 rows x 2881 columns]

In [23]:
# df1 = pd.DataFrame(df2.T, columns = column_name)
# display(df1)

In [33]:
day1 = pd.read_csv('/Users/Huang/Desktop/tests/testoneday.csv')
df1 = pd.DataFrame(day1)

day2 = pd.read_csv('/Users/Huang/Desktop/tests/testoneday2.csv')
df2 = pd.DataFrame(day2)

# display(df1, df2)
inputfile_dir = '/Users/Huang/Desktop/tests'
os.chdir(inputfile_dir)
file_list = os.listdir()
file_list.sort() 
# file_list = ['testoneday.csv', 'testoneday2.csv']

for i in range(2):    
    df = pd.read_csv( inputfile_dir + '/' + file_list[i], error_bad_lines=False)
    df.to_csv('/Users/Huang/Desktop/testall.csv', index=False, header=False, mode='a')


# put all data into one file

## leave the data with the same arrangement 

In [10]:
input_data = pd.read_csv("/Users/Huang/Documents/APIS/apis-emulator/data/input/Oist/house212_2019_avg.csv") 
input_data = input_data.fillna(method="ffill", inplace=False)
df = pd.DataFrame(input_data, columns=["timestamp", "ups_output_power"])

df.rename(columns={"timestamp":"Date"}, inplace=True)
# print(df.Date)
df["Date"] = pd.to_datetime(df.Date)

# df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
# df["Date"] = df["Date"].dt.date

# df["Time"] = df["Date"].dt.time
df["Date"] = df["Date"].dt.strftime('%Y/%m/%d')

display(df)


# df3 = df.unstack(0)
# print(df3)


# new_path = output_data_dir


# for path in file_list:
#     data = pd.read_csv(path)
#     df = pd.DataFrame(data, columns=["timestamp",
#                                      "ups_output_power",
#                                      ])
#     # export to csv files
#     df.to_csv(os.path.join(new_path, path), index=False)

Date  ups_output_power
0      2019/01/01        144.633333
1      2019/01/01        124.466667
2      2019/01/01        154.616667
3      2019/01/01        153.100000
4      2019/01/01        125.083333
...           ...               ...
15931  2019/12/31         72.050000
15932  2019/12/31         69.866667
15933  2019/12/31        133.783333
15934  2019/12/31         73.433333
15935  2019/12/31         15.350000

[15936 rows x 2 columns]

In [32]:
def old_loadDemand_Sample():
    global demand

    demand = {}
    # demand_data = np.genfromtxt('data/input/Sample/sample_load_data.csv', delimiter=',', names=True, dtype=None, encoding='utf-8')
    cols = list(range(6, 52+1, 2))
    cols.insert(0, 1)
    print(cols)
    # read column 2, col 7~53 for every 2 cols (1 hour per data point) from input data
    # replace our own data files to the /Sample/ folder
    demand_data = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_load_data.csv', delimiter=',', skiprows=1, usecols=cols)
    print(demand_data)
    
    for row in demand_data:
#         print(int(row[0]), row)
        cus_id = "E{0:03d}".format(int(row[0]))
#         print("cus_id", cus_id)
        if not demand.get(cus_id):
            demand[cus_id] = []
        demand[cus_id].append(row[1:])
#         print(demand[cus_id])
        
#     print("all id", demand)
    
    for cus_id in demand:
        demand[cus_id] = np.array(demand[cus_id])
        displayNames[cus_id] = "Sample_"+cus_id

    return demand

In [33]:
sample_load = old_loadDemand_Sample()
display(sample_load["E001"])
# print(len(sample_load["E001"]))

[1, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52]
[[  1.     0.13   0.13 ...   0.13   0.11   0.11]
 [  1.     0.13   0.13 ...   0.13   0.13   0.13]
 [  1.     0.14   0.14 ...   0.15   0.16   0.13]
 ...
 [100.     0.13   0.13 ...   0.49   0.5    0.91]
 [100.     0.13   0.13 ...   0.43   0.39   1.31]
 [100.     0.15   0.11 ...   0.55   1.25   0.61]]


array([[0.13, 0.13, 0.13, ..., 0.13, 0.11, 0.11],
       [0.13, 0.13, 0.13, ..., 0.13, 0.13, 0.13],
       [0.14, 0.14, 0.13, ..., 0.15, 0.16, 0.13],
       ...,
       [0.25, 0.23, 0.22, ..., 0.24, 0.24, 0.22],
       [0.2 , 0.2 , 0.18, ..., 0.23, 0.23, 0.26],
       [0.17, 0.17, 0.21, ..., 0.26, 0.25, 0.27]])

In [27]:
def PV_data():  # load house's PV production data
    global pv
    pv = {}

    our_data_all = pd.read_csv(
        '/Users/Huang/Documents/DQNBattery/data/fourhouses_2019_apis_solar.csv')
    our_data_all = our_data_all.fillna(method="ffill", inplace=False)
    our_data = our_data_all['pvc_charge_power'].values 
    print(our_data, len(our_data))
  
    for pv_col in our_data:
        print(int(pv_col[0]), pv_col)
        house_id = "E{0:03d}".format(int(pv_col[0]))
        print("houseID", house_id)
        if not pv.get(house_id):
            pv[house_id] = []
        pv[house_id].append(pv_col[1:])

    for house_id in pv:
        pv[house_id] = np.array(pv[house_id])
        displayNames[house_id] = "Oist" + house_id

#     pv = pv[house_id]

    return pv
        

In [28]:
displayNames = {}
pv_oist = PV_data()
display(pv_oist["E212"])


[0. 0. 0. ... 0. 0. 0.] 3824640


IndexError: invalid index to scalar variable.

In [15]:
# weather
def old_pvcUpdate_Sample():
    count_h = float(count_s)/3600

    weight = count_h-int(count_h)
    print("weight: ", weight)
    
    step_now = (int((count_h) / 24)), int((count_h) % 24)
    print("step_now: ", step_now)
    
    step_next = (int((count_h+1)/24)), int((count_h+1) % 24)
    print("step_next:", step_next)
    
    if int(count_h+1) >= sol.size:
        logger.debug("no more solar radiation data")
        return False
    for oesid in oesunits:
        oesunits[oesid]["emu"]["pvc_charge_power"] = round((1-weight)*sol[step_now] + weight*sol[step_next], 2)  # sol[W]
        print("pvc", oesunits)
        
    print("sol[step_now]", sol[step_now], "\n", "sol[step_next]", sol[step_next])
    print("pvc power", round((1-weight)*sol[step_now] + weight*sol[step_next], 2))
    print((1-weight)*sol[step_now] + weight*sol[step_next])
    
    return True

In [16]:
count_s = 525600 * 60 - 3600*9.5   # how many seconds have passed
count_h = float(count_s) / 3600
print("count_h = {:.4f} hours".format(count_h))
oesunits = {}
sol = np.loadtxt('/Users/Huang/Documents/APIS/apis-emulator/data/input/Sample/sample_solar_data.csv', delimiter=',')
print("sol.size: ", sol.size, "\n", "data size is {:.0f} days".format(int(sol.size/24)))

pvc = old_pvcUpdate_Sample()
print(pvc)

count_h = 8750.5000 hours
sol.size:  8760 
 data size is 365 days
weight:  0.5
step_now:  (364, 14)
step_next: (364, 15)
sol[step_now] 472.8 
 sol[step_next] 404.1
pvc power 438.45
438.45000000000005
True


## OUR DATA update, solar rad

In [26]:
def PVCUpdate():
#     count_s = 3600*12 # how many seconds have passed
    count_t = float(count_s)/30  # set counter for data which is collected every 30s
    print(count_t)
    weight = count_t-int(count_t)
    print("weight: ", weight)

    
#     step_now = (int((count_h) / 24)), int((count_h) % 24)
#     print("step_now: ", step_now)
    
#     step_next = (int((count_h+1)/24)), int((count_h+1) % 24)
#     print("step_next:", step_next)
    
    step_now =  (int((count_t) / 2880)+1) * int((count_t) % 2880)
    print("step_now: ", step_now, "\n", "our_data[step_now]", our_data[step_now])

    step_next = (int((count_t+1) / 2880)+1) * int((count_t+1) % 2880)
    print("step_next:", step_next, "\n", "our_data[step_next]", our_data[step_next])

    if int(count_t+1) >= our_data.size:
        logger.debug("no more our_data radiation data")
        return False
    for oesid in oesunits:
        oesunits[oesid]["emu"]["pvc_charge_power"] = round((1-weight)*our_data[step_now] + weight*our_data[step_next], 2)  # our_data[W]
        print("pvc", oesunits)
        
    print("our_data[step_now]", our_data[step_now], "\n", "our_data[step_next]", our_data[step_next])
    print("pvc power", round((1-weight)*our_data[step_now] + weight*our_data[step_next], 2))
    print((1-weight)*our_data[step_now] + weight*our_data[step_next])
    
    return True
    

In [27]:
# test for one day raw data (every 30s)
col = 4
# our_data = np.loadtxt('/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_all.csv', delimiter=',', skiprows=1, usecols=col)
# print(type(our_data))
our_data_all = pd.read_csv('/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_all.csv')#, delimiter=',', skiprows=1, usecols=col)
our_data_all = our_data_all.fillna(method="ffill", inplace=False)
our_data = our_data_all['pvc_charge_power'].values

# data_h212 = np.loadtxt("/Users/Huang/Documents/DQNBattery/data/house212_2019_sift/house212_20190101.csv")
print(our_data, "data size is", our_data.size, type(our_data))  # 0~2879
print(our_data[1566])
# pvc_212 = data_h212[""]
# plt.plot(our_data)
# plt.show()

count_s = 3600*24 - 30*1000.5 # how many seconds have passed
# count_t = float(count_s)/30  # set counter for data which is collected every 30s
# print(count_t)
# weight = count_t-int(count_t)
# print("weight: ", weight)

oesunits = {}

pvc = PVCUpdate()
print(pvc)


[0. 0. 0. ... 0. 0. 0.] data size is 956160 <class 'numpy.ndarray'>
788.0
1879.5
weight:  0.5
step_now:  1879 
 our_data[step_now] 255.0
step_next: 1880 
 our_data[step_next] 233.0
our_data[step_now] 255.0 
 our_data[step_next] 233.0
pvc power 244.0
244.0
True


## Our data updates, load

In [28]:
def LOADUpdate():
#     count_s = 3600*12 # how many seconds have passed
    count_t = float(count_s)/30  # set counter for data which is collected every 30s
    print(count_t)
    weight = count_t-int(count_t)
    print("weight: ", weight)

    step_now =  (int((count_t) / 2880)+1) * int((count_t) % 2880)
    print("step_now: ", step_now, "\n", "our_data[step_now]", our_data[step_now])

    step_next = (int((count_t+1) / 2880)+1) * int((count_t+1) % 2880)
    print("step_next:", step_next, "\n", "our_data[step_next]", our_data[step_next])

    if int(count_t+1) >= our_data.size:
        logger.debug("no more our_data load data")
        return False
    for oesid in oesunits:
        oesunits[oesid]["emu"]["ups_output_power"] = round((1-weight)*our_data[step_now] + weight*our_data[step_next], 2)  # our_data[W]
        print("load", oesunits)
        
    print("our_data[step_now]", our_data[step_now], "\n", "our_data[step_next]", our_data[step_next])
    print("pvc power", round((1-weight)*our_data[step_now] + weight*our_data[step_next], 2))
    print((1-weight)*our_data[step_now] + weight*our_data[step_next])
    
    return True
    

In [29]:
# test for one day raw data (every 30s)

our_data_all = pd.read_csv('/Users/Huang/Documents/DQNBattery/data/house212_2019_apis_all.csv')
our_data_all = our_data_all.fillna(method="ffill", inplace=False)
our_data = our_data_all['ups_output_power'].values

# data_h212 = np.loadtxt("/Users/Huang/Documents/DQNBattery/data/house212_2019_sift/house212_20190101.csv")
print(our_data, "data size is", our_data.size, type(our_data))  # 0~2879
print(our_data[1566])
# pvc_212 = data_h212[""]
# plt.plot(our_data)
# plt.show()

count_s = 3600*24 - 30*1000.5 # how many seconds have passed
# count_t = float(count_s)/30  # set counter for data which is collected every 30s
# print(count_t)
# weight = count_t-int(count_t)
# print("weight: ", weight)

oesunits = {}

load = LOADUpdate()
print(load)


[158. 152. 155. ...   0.   0.   0.] data size is 956160 <class 'numpy.ndarray'>
147.0
1879.5
weight:  0.5
step_now:  1879 
 our_data[step_now] 116.0
step_next: 1880 
 our_data[step_next] 115.0
our_data[step_now] 116.0 
 our_data[step_next] 115.0
pvc power 115.5
115.5
True


# put all houses data into one big file

**For the sake of limited size of the file, we just keep two values: pvc_charge_power and ups_output_power.
The houseID will be added for different houses, timestamp will be kept.**

In [30]:
# house 212, 213, 214, 215 four houses

def file_name_csv(input_data, output_data_dir):

    os.chdir(input_data)  # path of original csv data files
    # name = os.path.splitext(raw_data_dir)[0]  # get file name
    input_data = os.getcwd()  # read current file path

    file_list = os.listdir(input_data)


    new_path = output_data_dir
    for path in file_list:
        data = pd.read_csv(path)
        df = pd.DataFrame(data, columns=["timestamp",
                                         "pvc_charge_power"
                                         "ups_output_power",
                                         ])
        # export to csv files
        df.to_csv(os.path.join(new_path, path), index=False)

In [31]:
def get_one_house(input_file, houseID):
    
    data = pd.read_csv(input_file)
    df = pd.DataFrame(data, columns=["timestamp",
                                     "pvc_charge_power"
                                    ])
#     houseID_212 = '212'
    df.insert(0,'houseID', houseID)
    output_data = df

    return output_data

In [34]:
def get_one_house_load(input_file, houseID):
    
    data = pd.read_csv(input_file)
    df = pd.DataFrame(data, columns=["timestamp",
                                     "ups_output_power"
                                    ])
#     houseID_212 = '212'
    df.insert(0,'houseID', houseID)
    output_data = df

    return output_data

In [32]:
input_dir = '/Users/Huang/Documents/DQNBattery/data'
output_dir ='/Users/Huang/Documents//DQNBattery/data'
os.chdir(input_dir) 
input_dir = os.getcwd()

input_file_212 = input_dir + '/house212_2019_apis_all.csv'
houseID_212 = '212'

input_file_213 = input_dir + '/house213_2019_apis_all.csv'
houseID_213 = '213'

input_file_214 = input_dir + '/house214_2019_apis_all.csv'
houseID_214 = '214'

input_file_215 = input_dir + '/house215_2019_apis_all.csv'
houseID_215 = '215'

output_data_212 = get_one_house(input_file_212, houseID_212)
output_data_213 = get_one_house(input_file_213, houseID_213)
output_data_214 = get_one_house(input_file_214, houseID_214)
output_data_215 = get_one_house(input_file_215, houseID_215)

print(len(output_data_212))
print(len(output_data_213))
print(len(output_data_214))
print(len(output_data_215))

# export to one csv file

# df.to_csv(os.path.join(new_path, path), index=False)

956160
956160
956160
956160


In [35]:
output_loaddata_212 = get_one_house_load(input_file_212, houseID_212)
output_loaddata_213 = get_one_house_load(input_file_213, houseID_213)
output_loaddata_214 = get_one_house_load(input_file_214, houseID_214)
output_loaddata_215 = get_one_house_load(input_file_215, houseID_215)

## export to one csv file

df.to_csv(os.path.join(new_path, path), index=False)

In [33]:
output_all = output_data_212.append(output_data_213).append(output_data_214).append(output_data_215)
# display(test[956150:956170])

outputfile_name = 'fourhouses_2019_apis_solar.csv'
output_all.to_csv(output_dir + '/' + outputfile_name, index=False)

In [36]:
output_load_all = output_loaddata_212.append(output_loaddata_213).append(output_loaddata_214).append(output_loaddata_215)
# display(test[956150:956170])

outputfile_name2 = 'fourhouses_2019_apis_load.csv'
output_all.to_csv(output_dir + '/' + outputfile_name2, index=False)